In [45]:
# Part 1

import pandas as AP
ap = AP.read_csv("C:\\Assignments\\511\\adult.data", header = None)
ap

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [46]:
# Before removing ?

ap.shape

(32561, 15)

In [47]:
ap = ap[ ~ ap.isin([" ?"]).any(axis=1)]

In [48]:
# After removing ?

ap.shape

(30162, 15)

In [49]:
# Ordinal

ap[3].unique().tolist()

[' Bachelors',
 ' HS-grad',
 ' 11th',
 ' Masters',
 ' 9th',
 ' Some-college',
 ' Assoc-acdm',
 ' 7th-8th',
 ' Doctorate',
 ' Assoc-voc',
 ' Prof-school',
 ' 5th-6th',
 ' 10th',
 ' Preschool',
 ' 12th',
 ' 1st-4th']

In [64]:
edu_map = {
 ' Doctorate':14,
 ' Prof-school':13,
 ' Masters':12,
 ' Bachelors' :11,
 ' Assoc-acdm' :10,
 ' Assoc-voc' :10,
 ' some-college' :9,
 ' HS-grad':8,
 ' 12th':7,
 ' 11th': 6,
 ' 10th': 5,
 ' 9th':4,
 ' 7th-8th': 3,
 ' 5th-6th': 2,
 ' 1st-4th' :1,
 ' Preschool' :0
}
ap["Education"] = ap[3].map(edu_map)

In [65]:
ap

,0,1,2,3,4,5,6,7,8,9,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,...,False,False,False,False,False,False,False,True,False,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,False,False,False,False,False,False,False,True,False,False
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,False,False,False,False,False,False,False,True,False,False
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False

In [66]:
ap[14].unique().tolist()

[' <=50K', ' >50K']

In [67]:
edu_map2 = {' <=50K' : 0, ' >50K' : 1}
ap["Salary"] = ap[14].map(edu_map2)
ap

,0,1,2,3,4,5,6,7,8,9,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,...,False,False,False,False,False,False,False,True,False,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,False,False,False,False,False,False,False,True,False,False
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,False,False,False,False,False,False,False,True,False,False
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False

In [68]:
# Categorical

cC = [1,5,6,7,8,9,13]
for i in cC:
 ap = AP.concat([ap, AP.get_dummies(ap[i])],axis=1)

In [69]:
ap

,0,1,2,3,4,5,6,7,8,9,...,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,...,False,False,False,False,False,False,False,True,False,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,...,False,False,False,False,False,False,False,True,False,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,False,False,False,False,False,False,False,True,False,False
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,False,False,False,False,False,False,False,True,False,False
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,False,False,False,False,False,False,False,True,False,False
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,False,False,False,False,False,False,False,True,False,False

In [70]:
# Part 2

ap1 = AP.read_csv("C:\\Assignments\\511\\googleplaystore.csv")
ap1

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [71]:
# Before removing ?

ap1.shape

(10841, 13)

In [72]:
ap1 = ap1.dropna()

In [73]:
# After removing ?

ap1.shape

(9360, 13)

In [74]:
# No Use

ap1 = ap1.drop(columns=["App"])
ap1

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [75]:
ap1["Size"] = ap1["Size"].str.replace("M", "", regex=False)
ap1

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,ART_AND_DESIGN,4.1,159,19,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,ART_AND_DESIGN,3.9,967,14,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,ART_AND_DESIGN,4.5,215644,25,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.0,7,2.6,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,FAMILY,4.5,38,53,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,FAMILY,5.0,4,3.6,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,LIFESTYLE,4.5,398307,19,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [76]:
ap1["Installs"] = ap1["Installs"].str.replace("+", "", regex=False).str.replace(",", "", regex=False)
ap1

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,ART_AND_DESIGN,4.1,159,19,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,ART_AND_DESIGN,3.9,967,14,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,ART_AND_DESIGN,4.5,215644,25,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,FAMILY,4.5,38,53,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,LIFESTYLE,4.5,398307,19,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [77]:
ap1["Last Updated"] = AP.to_datetime(ap1["Last Updated"])
ap1["Last Updated"] = (ap1["Last Updated"] - AP.to_datetime(ap1["Last Updated"]).min()).dt.days
ap1

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,ART_AND_DESIGN,4.1,159,19,10000,Free,0,Everyone,Art & Design,2788,1.0.0,4.0.3 and up
1,ART_AND_DESIGN,3.9,967,14,500000,Free,0,Everyone,Art & Design;Pretend Play,2796,2.0.0,4.0.3 and up
2,ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2994,1.2.4,4.0.3 and up
3,ART_AND_DESIGN,4.5,215644,25,50000000,Free,0,Teen,Art & Design,2940,Varies with device,4.2 and up
4,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2952,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.0,7,2.6,500,Free,0,Everyone,Education,2585,1.0.0,4.1 and up
10836,FAMILY,4.5,38,53,5000,Free,0,Everyone,Education,2622,1.48,4.1 and up
10837,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,2968,1.0,4.1 and up
10839,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,1704,Varies with device,Varies with device
10840,LIFESTYLE,4.5,398307,19,10000000,Free,0,Everyone,Lifestyle,2987,Varies with device,Varies with device

In [81]:
# Ratio
ap2 = ap1[ [ "Rating", "Reviews", "Size", "Installs", "Price" ] ]

# Categorical
cC = ["Category", "Genres", "Type", "Content Rating", "Current Ver"]
for i in cC:
 ap2 = AP.concat([ap2, AP.get_dummies(ap1[i])],axis=1)

In [86]:
ap1["Current Ver"].unique().tolist()

['1.0.0',
 '2.0.0',
 '1.2.4',
 'Varies with device',
 '1.1',
 '1.0',
 '6.1.61.1',
 '2.9.2',
 '2.8',
 '1.0.4',
 '1.0.15',
 '3.8',
 '1.2.3',
 '3.1',
 '2.2.5',
 '5.5.4',
 '4.0',
 '2.2.6.2',
 '1.1.3',
 '1.5',
 '1.0.8',
 '1.03',
 '6.0',
 '6.7.12.2018',
 '1.2',
 '2.20',
 '1.1.0',
 '1.6',
 '2.1',
 '1.0.9',
 '1.3',
 '1',
 '2.0.1',
 '1.46',
 '1.6.1',
 '11.0',
 '3.0',
 '1.7.1',
 '2.5.1',
 '1.0.1',
 '2.493',
 '1.9.1',
 '1.7',
 '2.20 Build 02',
 '1.37',
 '0.2.1',
 '4.47.3',
 '1.9.7',
 '2.2.21',
 '2.9',
 '1.79',
 '2.3.5.1',
 '8.31',
 '1.1.5.0',
 '10.0.2',
 '1.10.3',
 '3.20.1',
 '1.0.3',
 '1.4',
 '4.6.5',
 '2.8.2',
 '4.0.3',
 '1.40',
 '1.5.18',
 '2.3.4',
 '2.17',
 '6.10.1',
 '2.3.0',
 '1.0.6',
 '1.9',
 '5.4',
 '3.0.1',
 '3.3.9',
 '1.20',
 '2.3.09',
 '1.4.2',
 '18.5',
 '1.2.13',
 '1.0.2.0',
 '3.1.89',
 '2.2.0',
 '1.9.2',
 '1.3.2',
 '3.2.1',
 '2.0.075',
 '1.911805270',
 '9.1.363',
 '1.1.6',
 '2.3.18',
 '15.0',
 '18.05.31+530',
 '5.0.6',
 '3.12',
 '2.0',
 '1.28',
 '6.0.8',
 '9.00.950462',
 '14.0',
 '3.05',
 '2.5.3',
 '7.0.4.6',
 '1.15',
 '3.1.7.9',
 '3.9.1',
 '3.4.2',
 '2.19.0.204537701',
 '9.7.14188',
 '4.9.10',
 '5.2.8',
 '3.3',
 '3.550.2',
 '4.6.30',
 '7.3.21',
 '1.1.13',
 '3.0.1.11 (Build 311)',
 '5.1.5',
 '2.3.6',
 '4.1.28165.0716',
 '99.0.0.35.75',
 '12.2.4',
 '1.0.6.8',
 '3.4.5',
 '2.5.6',
 '1.12.5',
 '4.9',
 '0.9.4',
 '1.1.07.6',
 '1.2.6',
 '3.9.2',
 '3.4.49',
 '1.5.2',
 '3.4.6',
 '1.12.0',
 '1.7.14',
 '3.24.1',
 '18.7',
 '3.19.005',
 '4.9.1',
 '6.1.2',
 '6.4.4',
 '3.7.5',
 '2.6.158',
 '5.20.7',
 '4.3.0.508',
 '10.46.2',
 '11.1.0',
 '1.2.287',
 '3.0.4651',
 '3.1.4.0',
 '3.3.0',
 '2.22.397',
 '2.0.19',
 '1.1.7.0',
 '2.11.3',
 '1.08',
 '3.4.3_world',
 '1.2.12',
 '6.3.0',
 '2.3.1',
 '3.1.0',
 '4.7.3',
 '3.16.0',
 '4.1.0',
 '1.7.7',
 '5.0.12',
 '4.3.0',
 '4.2.0.2',
 '1.01',
 '2.3.3',
 '2.4.25',
 '1.8.9',
 '37.0.0.7.163',
 '2.4.1',
 '5.29.3',
 '9.8.000000010492',
 '9.8.000000010501',
 '2.8.4.201036949',
 '1.3.4',
 '11.8.6',
 '24.6.6',
 '3.2.0.100171',
 '47.1.2249.129326',
 'R6.0.3',
 '5.2',
 '69.0.3497.24',
 '6.7.9.1',
 '1.60.0.31354-release',
 '11.4.0',
 '2.18.116',
 '7.5.1',
 '37.1.206017801.DR37_RC14',
 '7.5.3.20547',
 '2.2.7600',
 '12.8.5.1121',
 '9.9.0',
 '42.0.0.2059',
 '0.1.100944346',
 '6.1',
 '3.0.4',
 '7.3(800241)',
 '7.73',
 '4.98',
 '7.21',
 '3.47',
 '6.5.1',
 '5.65.0',
 '5.22.18.0006',
 '1.4.1.0',
 '2.2',
 '6.4.0.4',
 '4.5.1',
 '5.85.1',
 '196',
 '3.0.7',
 '1.26.001',
 '3.5.0',
 '8.1.2-6310',
 '5.86',
 '5.1.2-6310',
 '2018.1.715',
 '3.9.7',
 '1.286',
 '6.19.1',
 '2.17.3',
 '2.2.245',
 '4.5.4',
 '5.28.0',
 '5.403',
 '1.9.4.74',
 '5.0.9',
 '9.8.376',
 '2.3',
 '3.2.0',
 '2.3.17',
 '2.9.8',
 '7.2.29',
 '2.6.139',
 '11.10.1',
 '2.5.2',
 '6.1.3',
 '4.17.2',
 '3.5.0.1',
 '2.6.141',
 '4.19.0.2320',
 '6.6.5',
 '1.639',
 '4.4B',
 '1.308.us',
 '5.0.1',
 '2.45',
 '4.5.5',
 '1.2.1',
 '4.0.18',
 '1.6.5',
 '1.31.4',
 '1.230',
 '4.1.2',
 '15.8',
 '6.3.7',
 '4.8.5',
 '6.4.6',
 '2.3.0.1781',
 '4.3',
 '2.9.6',
 '3.8.75a',
 '3.0.0',
 '1.0.5',
 '1.31.3',
 '1.6.6',
 '2.0.5',
 '2.2.0.1748',
 '3.0.15',
 '2.4.0',
 '1.55',
 '12.0.4',
 '1.15.0',
 '6.4.1',
 '5.2.14',
 '8.7.2',
 '1.1.46',
 '2.8.0',
 '3.4.1.1',
 '5.5.7',
 '1.5.4.0',
 '4.9.2 (Oasis)',
 '3.10.5',
 '2.2.7',
 '1.17',
 '3.1.3',
 '0.0.73',
 '4.7.6',
 '5.2.9',
 '4.3.2',
 '3.6.3',
 '4.4.1',
 '5.16.2',
 '5.3.3.13289',
 '5.0.8',
 '0.1.11',
 '1.4.0',
 '2.4',
 '2.5',
 '8.2',
 '2.2.9',
 '3.52',
 '1.2.9',
 '2',
 '1.5-beta',
 '3.7',
 '4.813',
 '1.0.82',
 '4.1',
 '3.2.5',
 '5.0.0',
 '1.94.9',
 '1.2.8',
 '1.3.8',
 '2.1.8',
 '2.3.7',
 '2.9.0',
 '2.16.11.10',
 '1.2.0',
 '20.7.2',
 '2.24',
 '2.6.2',
 '2.51.0',
 '2.2.4',
 '3.7.0',
 '10',
 '2.8.1',
 '5.0.4',
 '2.15.1',
 '3.14.15',
 '1.10.0',
 '1.3.0',
 '4.7.0',
 '4.5.2',
 '5.7.2',
 '3.5.2',
 '5.5.2',
 '4.2.8',
 '7.2.3633',
 '1.8.1',
 '7.2.3634',
 '4.1.3',
 '2.48',
 '5.2.1',
 '0.29.74',
 '10.9.1',
 '4.2.3',
 '2.09',
 '2.3.9',
 '13.9.0.161',
 '3.6.0.115_FN',
 '8.5.2',
 '1.12.1',
 '4.8.2',
 '15.9.4',
 '9.12.5',
 '5.0',
 '4.21.1',
 '2.6.6',
 '1.16',
 '5.7.0',
 '2.4.4',
 '1.0.2',
 '5.7.1',
 '1.5-play',
 '1.1.1-play',
 '1.02',
 '2.13.5',
 '3.43.3',
 '2.05.0010',
 'v1.8b22p13',
 '3.7.3',
 '4.6.2',
 '4.0.5',
 '7.3',
 '2.6.6.11',
 '1.1.3.2',
 '9.1.4',
 '3.0.231.18141',
 '2.3.34 Prod',
 '2.08.78.2',
 '18.07.0',
 '3.5.2.2',
 '2.19.0',
 '2.9.43',
 '2.1.1',
 '6.18.3',
 '2.9.4',
 '01.01.66',
 '4.8.6',
 '3.1.4',
 '2.0.8',
 '11.45.0',
 '8.0626',
 '43',
 '4.18.1',
 '3.17.2',
 '3.3.1.41',
 '4.0.2',
 '16.0.0.437',
 '6.6.1',
 '3.3.1.42',
 '7.5.0',
 '4.003.1',
 '1.0.20',
 '1.0.64',
 '2.3.2',
 '8.1',
 '7.2.3',
 '4.2.0.8447',
 '4.426',
 '4.1.7',
 '8.4',
 '1.57',
 '1.5.0',
 '4.2.1',
 '4.3.6',
 '2018.07.31229',
 '4.0.19',
 '11.1.1',
 '1.75',
 '16.11.8',
 '1.14',
 '42.0',
 '2.2.2',
 '1.0.11',
 'Cannonau 3.11.11',
 '8.0bld14',
 '4.6.0',
 '20.1.0',
 '8.18',
 '10.78',
 '4.1.1-0-prod',
 '3.9.0',
 '5.16.0',
 '6.5.7',
 '3.115.27',
 '2.31.1',
 '3.0.5',
 '2.6.0',
 '1.17.2',
 '5.10.1.40699',
 '6.8.0.109',
 '6.28.0',
 '5.38.1',
 '2.7.4',
 '2.9.12',
 '3.22.0',
 '3.22.1',
 '2.70.206190089',
 '3.1.6.12',
 '6.39.1.4',
 '2.2.12',
 '2.5.0.26',
 '6.0.16',
 '2.29.01',
 '1.13.2.11',
 '2.0.4',
 '2.12.100',
 '2.53.2',
 '5.1.1',
 '1.14.1',
 '2.5.7',
 '2.1.4',
 '1.17.1',
 '1.4.11',
 '1.18.0',
 '3.1.16',
 '2.9.5',
 '16.6',
 '3.2.18.07.30',
 '1.9.9.9.3',
 '1.28.0.5402',
 '4.63',
 '2.10.3',
 '3.6.2',
 '3.04 - Beta',
 '6.8.2',
 '1.1.16',
 '1.1.39',
 '4.5.2.1',
 '3.0.22',
 '6.0.6',
 '2.131',
 '4.10.0',
 '6.0.2',
 '5.1',
 '2.34.29',
 '5.2.203',
 '8.44.2',
 '5.9.1.0',
 '7.8.8',
 '9.7.0',
 '6.7.0',
 '6.29.37589',
 '5.15.0',
 '18.6.0.10',
 '2.12',
 '3.2.0d',
 '3.1.5',
 '4.0.30',
 '1.9.117',
 '5.2.2',
 '7.12',
 '4.3.3',
 '6.0.1',
 '2.14.36',
 '4.11.1',
 '3.3.21',
 '5.3.8',
 '3.5.5',
 '3.3.6',
 '7.9.0.0',
 '2.1.0',
 '5.8.5',
 '3.2.7',
 '4.26',
 '1.2.2',
 '3.6.6',
 '4.0.0.427',
 '3.17.1.0',
 '24.5.0',
 '1.4.4',
 '2.0.3',
 '2.76.2.0-android',
 '5.7.23',
 '4.2.6',
 '9.15.0.2020',
 '2.6.15',
 '3.1.14',
 '2.4.11',
 '1.161.10002',
 '11.11.1',
 '4.11.3',
 '1.0.7',
 '1.0.14',
 '5.23',
 '5.31.75',
 '1.0.26',
 'p5.7.1',
 '3.0.6',
 '1.1.22',
 '18.7.1',
 '4.0.1',
 '1.0.12',
 '2.17.0',
 '2.6',
 '6.15.0',
 '3.401',
 '6.5.3',
 '112.0',
 '5.13.0',
 '3.48',
 '2.48.3',
 '5.3',
 '5.14.0',
 '4.4',
 '10.0',
 '8.2.0',
 '7.2.5',
 '6.2.73',
 '6.7',
 '16.0',
 '7.0',
 '3.1.9',
 '2.6.1',
 '1.29.15',
 '3.6.4',
 '2.0.16',
 '3.22',
 '7.3.4-play',
 '2.9.18',
 '10.24',
 '37',
 '5.0.2',
 '5.5.1',
 '8.8.14',
 '3.19.4',
 '3.3.0(1)',
 '1.11.4',
 '4.5.1.123',
 '10.2.0',
 '4.9.8.1',
 'Public.Heal',
 '1.31.0-15160.950adac99',
 '6.3.1',
 '1.92',
 '4.8.0',
 '8.2.0_8',
 '7.4',
 '9.8.1.7425',
 '3.5.9',
 '9.6.8',
 '8.2.1',
 '3.6',
 '3.10.8',
 '220.0',
 '3.2.4',
 '2.4.2',
 '2.6.0.287',
 '858',
 '7.9.0',
 '4.7.13',
 '2.0.6.9',
 '1.22.0',
 'v3.1.1',
 '1.6.1.2',
 '4.5.15',
 '1.7.3',
 '5.20.38',
 '1.7.2.10',
 '6.7.5',
 '1.02.2018.11',
 '6.0.0',
 '1.8',
 '5.28',
 '8.0.20180212',
 '3.00',
 '5.9.1',
 '8.0',
 '4.2.2',
 '5.1.2',
 '5.3.0.54.7',
 '9.0',
 '10.19',
 '5.2.4(881)',
 '1.0.0.21_180410',
 '5.8',
 '4.90',
 '16.7.1',
 '3.9.3',
 '6.2.0',
 '8.00.775375',
 '2.4.12-r244',
 '9.6.3',
 '10.19.0.0',
 '2.15',
 '1.1.1',
 '1.5.1',
 'Version:6.97',
 '1.5.3',
 '7.0.8',
 '02.00.06',
 '5.1.3',
 '9.4.2',
 '6.2.1',
 '3.8.15',
 '4.35',
 '5.2.2018010801-1',
 '2.7.3',
 '3.9.5',
 '8.5.1',
 '2.0.9',
 '3.1.2.1',
 '1.6.2',
 '9.1.0',
 '2.2.6',
 '12.1.0',
 '8.3.3',
 '5.600.42',
 '3.1.6',
 '5.800.04',
 '3.1.8',
 '2.347.225742',
 '1.90.0',
 '1.129.0.2',
 '2.137.0',
 '1.20.1',
 '1.49.1',
 '1.4.77',
 '2.6.9',
 '2.2.00',
 '3.8.5.Go',
 '1.118.4',
 '10.322.16',
 '6.6.3',
 '2.2.3181',
 '4.0.0',
 '5.13.007',
 '4.8.4',
 '1.4.0.1',
 '7.9.3',
 '1.0.16',
 '2.21.5',
 '5.66',
 '3.5',
 '1.3.7',
 '2.1.10',
 '1.37.2',
 '1.0.27',
 '5.1.8',
 '3.7.2.51',
 '3.7.2',
 '3196',
 '1.751',
 '5423',
 '1.0.47',
 '1.21.0',
 '2.12.5',
 '4.8.0.132',
 '1.5.4',
 '1.7.40',
 '2.8.2.59',
 '5.064',
 '3.3.3179',
 '1.7.2',
 '2.10.2',
 '1.2.7',
 '3.1.0.226',
 '0.111.3',
 '5.200',
 '1.24',
 '1.7.0',
 '1.4.6',
 '2.0.6',
 '1.0.1.049',
 '2.5.0',
 '2.79.0',
 '1.3.3',
 '0.7.0',
 '1.8.2',
 '1.4.51',
 '1.3.1',
 '3.04.1',
 '1.1.4',
 '3.00.11034',
 '1.9.3',
 '1.2.5',
 '1.11.0',
 '1.8.0.900',
 '5.6.5',
 '2.2.3',
 '4.9.31',
 '3.6.0',
 '0.5.4',
 '1.180271.184729',
 '1.3.205',
 '2.1.1.4.0',
 '1.250.078',
 '2.0.2',
 '1.05.20',
 '3.30.4.83',
 '2.0081_206',
 '2.2.1',
 '2.1.2',
 '1.2.1.1712080',
 '2.21.1',
 '1.13.12',
 '5.39.1',
 '5.8.1',
 '19.1.0',
 '1.3.15',
 '2.3.5',
 '4.6.2.46103',
 '12.0.4.62276',
 '1.93',
 '1.8.225278',
 '3.0.2',
 '1.14.0',
 '1.76',
 '1.1.8',
 '1.1.40',
 '1_39_93',
 '79.0',
 '1.9.38',
 '1.8.20',
 '1.1.5',
 '2.11.1',
 '1.8.4',
 '108',
 '3.1.1',
 '1.1.7',
 '2.2.8',
 '0.5.8',
 '8',
 '1.15.2',
 '1.11.2',
 '4.1.1',
 '2.6.61',
 '6.2',
 '2.11.2',
 '57.0.8',
 '2.9.3181',
 '1.0.109',
 '3.15',
 '60',
 '1.7.04',
 '1.3.35',
 '2.5.3182',
 '1.10.12',
 '1.4.12',
 '1.9.3901',
 '1.49',
 '1.24.3181',
 '1.1.6.7',
 '1.8.3181',
 '2.0.3165',
 '1.7.101',
 '2.2.3169',
 '1.0.3122',
 '8.25.10.00',
 '2.7',
 '1.2.3-play',
 '2.3.3122',
 '3.5.3183',
 '8.4.3180',
 '1.73',
 '2.2.3172',
 '1.0.89',
 '2.180723',
 '1.1.2',
 '2.0.5.0',
 '8.25.10.01',
 '1.6.4',
 '2.0.7.4',
 '5.3.11',
 '7.32',
 '3.4.0',
 '10.180530',
 '149',
 '1.8.3',
 '1.180702',
 '3.2.473.202',
 '1.221',
 '1.1.9',
 '1.4.3',
 '6.7.5222',
 '1.1.23',
 '1.28.01',
 '2.1.6579',
 '1.47',
 '1.20.2',
 '3.2.0h',
 '2.1.20',
 '3.49',
 '37893',
 '3.200.18289',
 '1.4.2.1',
 '1.19',
 '2.4.9',
 '18.1',
 '3.6.1',
 '3.7.2.7',
 '2.19.01',
 '7.5',
 '1.15.3028.0',
 '1.6.3028.0',
 '2.9.7',
 '1.2.16',
 '1.19.56.434',
 '0.1.0',
 '4.2',
 '20180609',
 '2.4.15',
 '3.3.1',
 '1.16.5',
 '18.2',
 '2.0.7',
 '3.46',
 '2.2.54',
 '1.3.51',
 '1.38.0',
 '3.6.17',
 '7.2.0',
 '1.35.23',
 '28.0.14',
 '6.14.091',
 '6.4.0',
 '1.5.2.1',
 '7.0.1',
 '3.0.1.0',
 '6.5.0',
 '2018.5.47',
 '19.0',
 '1.17.0',
 '7.6.14',
 '7',
 '1.10.0.user.pro.release',
 '4.1.5 (Steglitz)',
 '7.1.17',
 '3.4.3',
 '1.50',
 '2.29',
 '4.4.5',
 '6.0.4',
 '2.1.35',
 '5.4.8',
 '3.19',
 '1.1.0.0.1487',
 '3.27.3',
 '3.25.0',
 '8.0.226',
 '5.9.6',
 '6.02.000',
 '3.18.2',
 '7.4.1',
 '2.11.0',
 '4.36',
 '1.0.02',
 '2.25.0',
 '3.52.1',
 '2.1.3',
 '1.16.0',
 '25.3.1',
 '5.11',
 '1.3.185',
 '1.7.1 (946)',
 '4.23.0',
 '3.8.0',
 '1.2.3.2',
 '4.4.7',
 '2.1.11',
 '4.3.2.315',
 '2.6.5',
 '3.16.4.1669',
 '2.7.36',
 '4.9.6',
 '2.1.0.372',
 '3.5.7',
 '1.0.0.10',
 '4.5.3',
 '2.7.38',
 '1.6.17',
 '3.1-2018 â€“ (13)',
 '6.6',
 '2.7.6',
 '1.830.0.564-(e405bb2)',
 '1.0.72',
 '300000.1.11',
 '0.1',
 '5.0.16',
 'PN.1.0',
 '0.1.2',
 '1.0.51.0.3',
 '3.4.0.10',
 '10.4.1.015_05',
 '1.12',
 '5.51',
 '10.4.1.000_00',
 '4.0.9',
 '3.0.8',
 '2.5.0 b665',
 '0.6.88',
 '1.0.32',
 '43.0',
 '4.4.3',
 '0.0.1',
 '1.9.0.0',
 '1.4.15-free',
 '2.4.12',
 '0.1.1',
 '4.95.4',
 '2.1.6',
 '2.6.10',
 '2.1.3.2',
 'T4.6.5-tl2.0.1',
 '1.8.19179',
 '13.0',
 '4.2.4',
 '4.81',
 '8.00.752746',
 '1.23.3.0',
 '50.2 lite',
 '4.1.202',
 '3.10.26',
 '7.3.1',
 '3.8.1',
 '7.0.7',
 '14.0.13',
 '7.23.4',
 '2.69',
 '4.6.2.0',
 '1.8.0',
 '27.0',
 '10.6.3',
 '4.18.962.5',
 '2.16',
 '5.4.7.1',
 '16.14.0.850',
 '4.20.5',
 '2.25.17',
 '14.2.1',
 '16.14.0.100',
 '11.7.3.0',
 '10.2.1',
 '3.8.2.2',
 '6.3.8',
 '2.8.7',
 '4.16.2',
 '4.26.7',
 '3.2.6',
 '4.9.3',
 '4.7.1',
 '4.9.5',
 '3.11.1',
 '4.7.5',
 '3.27.1',
 ...]

In [87]:
# Ordinal
edu_map3 ={"Varies with device":0,
 "1.0 and up":1,
 "1.5 and up":2,
 "1.6 and up":3,
 "2.0 and up":4,
 "2.0.1 and up":5,
 "2.1 and up":6,
 "2.2 and up":7,
 "2.3 and up":8,
 "2.3.3 and up":9,
 "3.0 and up":10,
 "3.1 and up":11,
 "3.2 and up":12,
 "4.0 and up":13,
 "4.0.3 - 7.1.1":14,
 "4.0.3 and up":15,
 "4.1 - 7.1.1":16,
 "4.1 and up":17,
 "4.2 and up":18,
 "4.3 and up":19,
 "4.4 and up":20,
 "4.4W and up":21,
 "5.0 - 6.0":22,
 "5.0 - 8.0":23,
 "5.0 and up":24,
 "5.1 and up":25,
 "6.0 and up":26,
 "7.0 - 7.1.1":27,
 "7.0 and up":28,
 "7.1 and up":29,
 "8.0 and up":30
}
ap2['Android Ver'] = ap1['Android Ver'].map(edu_map3)
ap2['Last Updated'] = ap1['Last Updated']

In [88]:
ap2

,Rating,Reviews,Size,Installs,Price,ART_AND_DESIGN,AUTO_AND_VEHICLES,BEAUTY,BOOKS_AND_REFERENCE,BUSINESS,...,v6.7.14,v67_slk3.0_20180115_01,v7.0.02.3.0516.1_06_0713,v7.0.7.1.0625.1_06_0629,v7.0.9.1.0526.1_06_0704,v8.0.1.8.0629.1,v8[1.0.10],version 0.994,Android Ver,Last Updated
0,4.1,159,19,10000,0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,15,2788
1,3.9,967,14,500000,0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,15,2796
2,4.7,87510,8.7,5000000,0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,15,2994
3,4.5,215644,25,50000000,0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,18,2940
4,4.3,967,2.8,100000,0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,20,2952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,4.0,7,2.6,500,0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,17,2585
10836,4.5,38,53,5000,0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,17,2622
10837,5.0,4,3.6,100,0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,17,2968
10839,4.5,114,Varies with device,1000,0,False,False,False,True,False,...,False,False,False,False,False,False,False,False,0,1704
10840,4.5,398307,19,10000000,0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,0,2987